/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedeemGiftRouteImport } from './routes/redeem-gift'
import { Route as IndexRouteImport } from './routes/index'

const RedeemGiftRoute = RedeemGiftRouteImport.update({
  id: '/redeem-gift',
  path: '/redeem-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redeem-gift': typeof RedeemGiftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redeem-gift': typeof RedeemGiftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redeem-gift': typeof RedeemGiftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redeem-gift'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redeem-gift'
  id: '__root__' | '/' | '/redeem-gift'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedeemGiftRoute: typeof RedeemGiftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redeem-gift': {
      id: '/redeem-gift'
      path: '/redeem-gift'
      fullPath: '/redeem-gift'
      preLoaderRoute: typeof RedeemGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedeemGiftRoute: RedeemGiftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
